### ISSUE TITLE
SetMinHeight is ignored

### ISSUE THREAD

**Issue by antonmedv** [76creates/stickers#14]
Hi,

Looks like SetMinHeigth is now working as expected.

**Comment by 76creates** [comment]
Hey @antonmedv, cant se any issues with it first hand, here is the diff of the `example/flex-box-simple/main.go` that I used to check functionality:
~~~diff
diff --git a/example/flex-box-simple/main.go b/example/flex-box-simple/main.go
index f2331d4..db08114 100644
--- a/example/flex-box-simple/main.go
+++ b/example/flex-box-simple/main.go
@@ -43,7 +43,7 @@ func main() {
 
        rows := []*flexbox.Row{
                m.flexBox.NewRow().AddCells(
-                       flexbox.NewCell(1, 6).SetStyle(style1),
+                       flexbox.NewCell(1, 6).SetStyle(style1).SetMinWidth(20),
                        flexbox.NewCell(1, 6).SetStyle(style2),
                        flexbox.NewCell(1, 6).SetStyle(style3),
                ),

~~~

Please provide code sample with reproducible issue, also please not that this function works only with `HorizontalFlexBox` like noted in the comment.

**Comment by antonmedv** [comment]
I missed the part about HorizontalFlexBox. This was the issue. Also word height is spelled incorrectly in the source code.
