### ISSUE TITLE
Randomly Column Order Changes

### ISSUE THREAD

**Issue by csg33k** [76creates/stickers#19]
I have a very simple app and I noticed when I hit "tab" too many times the order of the columns as they are rendered occasionally changes.

I have a repo with the code at fault.  https://github.com/csg33k/bubbles/tree/main/02_preview but for context to capture it in the issue.

```go
func NewModel() *rootModel {
	srv := NewSurvey()
	modelsMap := make(map[focusIndex]tea.Model)
	mainModel := NewGreetingModel("Welcome to the Greeter Builder\n")
	previewModel := NewPreviewModel(&srv)
	modelsMap[Main] = mainModel
	modelsMap[Preview] = previewModel
	m := flexbox.NewHorizontal(0, 0)
	columns := []*flexbox.Column{
		m.NewColumn().AddCells(
			flexbox.NewCell(1, 1).SetContent(mainModel.View()),
		),
		m.NewColumn().AddCells(
			flexbox.NewCell(1, 1).SetContent(previewModel.View()),
		),
	}
	m.AddColumns(columns)

	return &rootModel{
		flexBox:      m,
		paneSelected: Main,
		answers:      &srv,
		modelsMap:    modelsMap,
	}
}

func (r *rootModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	var (
		cmd  tea.Cmd
		cmds []tea.Cmd
	)

	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		r.flexBox.SetWidth(msg.Width)
		r.flexBox.SetHeight(msg.Height)
	case tea.KeyMsg:
		key := msg.String()
		switch key {
		case "j":
			r.answers.Age = 42
		case "tab":
			r.paneSelected = (r.paneSelected + 1) % 2
		case "ctrl+c", "esc":
			return r, tea.Quit
		}
	}

	ndx := 0
	//Update all models
	for _, val := range r.modelsMap {
		_, cmd = val.Update(msg)
		if ndx == int(r.paneSelected) {
			content := activeStyle.Render(val.View())
			r.flexBox.GetColumn(ndx).GetCell(0).SetContent(content)
		} else {
			r.flexBox.GetColumn(ndx).GetCell(0).SetContent(val.View())
		}
		cmds = append(cmds, cmd)
		ndx++
	}
	return r, tea.Batch(cmds...)
}
```

Is there anything I'm doing wrong that would cause this issue?

I also attached an image of the behavior I'm seeing.  The only thing I'm doing is running the app and hitting tab till I see the behavior.

![preview](https://github.com/user-attachments/assets/f9c8c968-321c-48c3-81a9-1ab96f5b28c0)

**Comment by giapoldo** [comment]
Only with "tab"? Because if your data is a map, order is not guaranteed using a range.

**Comment by csg33k** [comment]
Doh sorry about that.  reading over that code again it makes perfect sense.  thank you for your response.

**Comment by giapoldo** [comment]
> Doh sorry about that. reading over that code again it makes perfect sense. thank you for your response.

Don't worry. I only realized this because the same happened to me, lol.
