### ISSUE TITLE
Flexbox does not render borders correctly

### ISSUE THREAD

**Issue by Cro0ksy** [76creates/stickers#8]
Hello,
no matter how i attempt to tweak the boxes, there seems to be no way to get them to render the borders on all 4 sides. Is this just a problem i am having, or is this not supported?
I figured it cant draw the right border because the Flexbox always takes 100% width, even if this means not showing other content that would be on the side. Is there a way to prevent this?

![Border_Issue](https://user-images.githubusercontent.com/80394345/209444394-2a7c608c-3685-43f4-8f7d-7b4aed9e432f.png)

**Comment by 76creates** [comment]
Hey @Cro0ksy, thanks for reporting an issue!
I pushed a fix in this commit https://github.com/76creates/stickers/commit/b66e7226c01ece911ac3288b9de65ff15bacb612, pull it and give it a try, should work good ⚡

**Comment by Cro0ksy** [comment]
> Hey @Cro0ksy, thanks for reporting an issue! I pushed a fix in this commit [b66e722](https://github.com/76creates/stickers/commit/b66e7226c01ece911ac3288b9de65ff15bacb612), pull it and give it a try, should work good zap

Hello, thanks for the fast reply, though it appears as if the issue still isn't resolved.
The Border still does not get rendered on all 4 sides of the flexbox. 
For good measure i will provide the flexbox, as well as the style definitions below.

```go
var styleContent = lipgloss.NewStyle().
BorderStyle(lipgloss.RoundedBorder()).Align(lipgloss.Center)

func loadingModule() model {
	return model{
		flexbox:   stickers.NewFlexBox(0, 0).SetStyle(styleContent),
	}
}

func (m model) Init() tea.Cmd {
	m.flexbox.AddRows([]*stickers.FlexBoxRow{
		m.flexbox.NewRow().AddCells(
			[]*stickers.FlexBoxCell{
				stickers.NewFlexBoxCell(1, 1),
				stickers.NewFlexBoxCell(1, 1),
			},
		),
	})
	return nil
}

func (m model) View() string {
	m.flexbox.Row(0).Cell(0).SetContent("Content")
	m.flexbox.Row(0).Cell(1).SetContent("Content")
	return m.flexbox.Render()
}
```

Hope this helps

**Comment by 76creates** [comment]
Ah, I see, I fixed `FlexBoxCell` but you are setting a style on a `FlexBox`, whole other thing. Ive done a bit of digging and found series of miscalculations, now it will work _as a charm_(all puns intended).

Please pull new version and give it a go, you will note that style inheritance has been changed as well, you will want to check that out if you intended to pass down border style to cells ⚡ 


![proof](https://imgur.com/OXAPACN.png)

**Comment by 76creates** [comment]
@Cro0ksy is all well rendered, we can close this one?

**Comment by Cro0ksy** [comment]
Works perfectly, thanks a lot!
