### ISSUE TITLE
use variadic function to add cells

### ISSUE THREAD

**Issue by jon4hz** [76creates/stickers#9]
Hi, 
This library is absolutely brilliant! 
However constructing the flexbox rows is very verbose and can get a bit messy. 

What do you think about using a variadic function for the `AddCells()` method? 
```go
func (r *FlexBoxRow) AddCells(cells ...*FlexBoxCell) *FlexBoxRow
```

The construction could be simplified from:
```go
rows := []*stickers.FlexBoxRow{
		m.flexBox.NewRow().AddCells(
			[]*stickers.FlexBoxCell{
				stickers.NewFlexBoxCell(1, 1).SetStyle(style1),
				stickers.NewFlexBoxCell(1, 1).SetStyle(style2),
			},
		),
		m.flexBox.NewRow().AddCells(
			[]*stickers.FlexBoxCell{
				stickers.NewFlexBoxCell(1, 1).SetStyle(style3),
				stickers.NewFlexBoxCell(1, 1).SetStyle(style4),
			},
		),
	}
```
To:
```go
rows := []*stickers.FlexBoxRow{
		m.flexBox.NewRow().AddCells(
			stickers.NewFlexBoxCell(1, 1).SetStyle(style1),
			stickers.NewFlexBoxCell(1, 1).SetStyle(style2),
		),
		m.flexBox.NewRow().AddCells(
			stickers.NewFlexBoxCell(1, 1).SetStyle(style3),
			stickers.NewFlexBoxCell(1, 1).SetStyle(style4),
		),
	}
```

**Comment by 76creates** [comment]
Hey @jon4hz, thanks for investing time into stickers ⚡ 
Yes, that looks good for sure, it should be extended to other relevant functions like `AddRows`, and examples, as well.
Please submit pull request, don't forget to update the changelog 🚢

**Comment by 76creates** [comment]
Just noticed you have created it already 😅

**Comment by 76creates** [comment]
This has been merged
